<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Regression I: K-nearest neighbours | Data Science: A First Introduction</title>
  <meta name="description" content="A textbook for teaching a first introduction to data science." />
  <meta name="generator" content="bookdown 0.19 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Regression I: K-nearest neighbours | Data Science: A First Introduction" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A textbook for teaching a first introduction to data science." />
  <meta name="github-repo" content="UBC-DSCI/introduction-to-datascience" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Regression I: K-nearest neighbours | Data Science: A First Introduction" />
  
  <meta name="twitter:description" content="A textbook for teaching a first introduction to data science." />
  

<meta name="author" content="Tiffany Timbers, Trevor Campbell and Melissa Lee" />


<meta name="date" content="2020-12-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="classification-continued.html"/>
<link rel="next" href="regression2.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Science: A First Introduction</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#why-read-this-book"><i class="fa fa-check"></i>Why read this book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#structure-of-the-book"><i class="fa fa-check"></i>Structure of the book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#software-information-and-conventions"><i class="fa fa-check"></i>Software information and conventions</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgments"><i class="fa fa-check"></i>Acknowledgments</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html"><i class="fa fa-check"></i>About the Authors</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#chapter-learning-objectives"><i class="fa fa-check"></i><b>1.1</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#jupyter-notebooks"><i class="fa fa-check"></i><b>1.2</b> Jupyter notebooks</a></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#loading-a-spreadsheet-like-dataset"><i class="fa fa-check"></i><b>1.3</b> Loading a spreadsheet-like dataset</a></li>
<li class="chapter" data-level="1.4" data-path="introduction.html"><a href="introduction.html#assigning-value-to-a-data-frame"><i class="fa fa-check"></i><b>1.4</b> Assigning value to a data frame</a></li>
<li class="chapter" data-level="1.5" data-path="introduction.html"><a href="introduction.html#creating-subsets-of-data-frames-with-select-filter"><i class="fa fa-check"></i><b>1.5</b> Creating subsets of data frames with <code>select</code> &amp; <code>filter</code></a><ul>
<li class="chapter" data-level="1.5.1" data-path="introduction.html"><a href="introduction.html#using-select-to-extract-multiple-columns"><i class="fa fa-check"></i><b>1.5.1</b> Using <code>select</code> to extract multiple columns</a></li>
<li class="chapter" data-level="1.5.2" data-path="introduction.html"><a href="introduction.html#using-select-to-extract-a-range-of-columns"><i class="fa fa-check"></i><b>1.5.2</b> Using <code>select</code> to extract a range of columns</a></li>
<li class="chapter" data-level="1.5.3" data-path="introduction.html"><a href="introduction.html#using-filter-to-extract-a-single-row"><i class="fa fa-check"></i><b>1.5.3</b> Using <code>filter</code> to extract a single row</a></li>
<li class="chapter" data-level="1.5.4" data-path="introduction.html"><a href="introduction.html#using-filter-to-extract-rows-with-values-above-a-threshold"><i class="fa fa-check"></i><b>1.5.4</b> Using <code>filter</code> to extract rows with values above a threshold</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="introduction.html"><a href="introduction.html#exploring-data-with-visualizations"><i class="fa fa-check"></i><b>1.6</b> Exploring data with visualizations</a><ul>
<li class="chapter" data-level="1.6.1" data-path="introduction.html"><a href="introduction.html#using-ggplot-to-create-a-scatter-plot"><i class="fa fa-check"></i><b>1.6.1</b> Using <code>ggplot</code> to create a scatter plot</a></li>
<li class="chapter" data-level="1.6.2" data-path="introduction.html"><a href="introduction.html#formatting-ggplot-objects"><i class="fa fa-check"></i><b>1.6.2</b> Formatting ggplot objects</a></li>
<li class="chapter" data-level="1.6.3" data-path="introduction.html"><a href="introduction.html#changing-the-units"><i class="fa fa-check"></i><b>1.6.3</b> Changing the units</a></li>
<li class="chapter" data-level="1.6.4" data-path="introduction.html"><a href="introduction.html#coloring-points-by-group"><i class="fa fa-check"></i><b>1.6.4</b> Coloring points by group</a></li>
<li class="chapter" data-level="1.6.5" data-path="introduction.html"><a href="introduction.html#putting-it-all-together"><i class="fa fa-check"></i><b>1.6.5</b> Putting it all together</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="reading.html"><a href="reading.html"><i class="fa fa-check"></i><b>2</b> Reading in data locally and from the web</a><ul>
<li class="chapter" data-level="2.1" data-path="reading.html"><a href="reading.html#overview"><i class="fa fa-check"></i><b>2.1</b> Overview</a></li>
<li class="chapter" data-level="2.2" data-path="reading.html"><a href="reading.html#chapter-learning-objectives-1"><i class="fa fa-check"></i><b>2.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="2.3" data-path="reading.html"><a href="reading.html#absolute-and-relative-file-paths"><i class="fa fa-check"></i><b>2.3</b> Absolute and relative file paths</a></li>
<li class="chapter" data-level="2.4" data-path="reading.html"><a href="reading.html#reading-tabular-data-from-a-plain-text-file-into-r"><i class="fa fa-check"></i><b>2.4</b> Reading tabular data from a plain text file into R</a><ul>
<li class="chapter" data-level="2.4.1" data-path="reading.html"><a href="reading.html#skipping-rows-when-reading-in-data"><i class="fa fa-check"></i><b>2.4.1</b> Skipping rows when reading in data</a></li>
<li class="chapter" data-level="2.4.2" data-path="reading.html"><a href="reading.html#read_delim-as-a-more-flexible-method-to-get-tabular-data-into-r"><i class="fa fa-check"></i><b>2.4.2</b> <code>read_delim</code> as a more flexible method to get tabular data into R</a></li>
<li class="chapter" data-level="2.4.3" data-path="reading.html"><a href="reading.html#reading-tabular-data-directly-from-a-url"><i class="fa fa-check"></i><b>2.4.3</b> Reading tabular data directly from a URL</a></li>
<li class="chapter" data-level="2.4.4" data-path="reading.html"><a href="reading.html#previewing-a-data-file-before-reading-it-into-r"><i class="fa fa-check"></i><b>2.4.4</b> Previewing a data file before reading it into R</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="reading.html"><a href="reading.html#reading-data-from-an-microsoft-excel-file"><i class="fa fa-check"></i><b>2.5</b> Reading data from an Microsoft Excel file</a></li>
<li class="chapter" data-level="2.6" data-path="reading.html"><a href="reading.html#reading-data-from-a-database"><i class="fa fa-check"></i><b>2.6</b> Reading data from a database</a><ul>
<li class="chapter" data-level="2.6.1" data-path="reading.html"><a href="reading.html#connecting-to-a-database"><i class="fa fa-check"></i><b>2.6.1</b> Connecting to a database</a></li>
<li class="chapter" data-level="2.6.2" data-path="reading.html"><a href="reading.html#interacting-with-a-database"><i class="fa fa-check"></i><b>2.6.2</b> Interacting with a database</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="reading.html"><a href="reading.html#writing-data-from-r-to-a-.csv-file"><i class="fa fa-check"></i><b>2.7</b> Writing data from R to a <code>.csv</code> file</a></li>
<li class="chapter" data-level="2.8" data-path="reading.html"><a href="reading.html#scraping-data-off-the-web-using-r"><i class="fa fa-check"></i><b>2.8</b> Scraping data off the web using R</a><ul>
<li class="chapter" data-level="2.8.1" data-path="reading.html"><a href="reading.html#html-and-css-selectors"><i class="fa fa-check"></i><b>2.8.1</b> HTML and CSS selectors</a></li>
<li class="chapter" data-level="2.8.2" data-path="reading.html"><a href="reading.html#are-you-allowed-to-scrape-that-website"><i class="fa fa-check"></i><b>2.8.2</b> Are you allowed to scrape that website?</a></li>
<li class="chapter" data-level="2.8.3" data-path="reading.html"><a href="reading.html#using-rvest"><i class="fa fa-check"></i><b>2.8.3</b> Using <code>rvest</code></a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="reading.html"><a href="reading.html#additional-resources"><i class="fa fa-check"></i><b>2.9</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="wrangling.html"><a href="wrangling.html"><i class="fa fa-check"></i><b>3</b> Cleaning and wrangling data</a><ul>
<li class="chapter" data-level="3.1" data-path="wrangling.html"><a href="wrangling.html#overview-1"><i class="fa fa-check"></i><b>3.1</b> Overview</a></li>
<li class="chapter" data-level="3.2" data-path="wrangling.html"><a href="wrangling.html#chapter-learning-objectives-2"><i class="fa fa-check"></i><b>3.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="3.3" data-path="wrangling.html"><a href="wrangling.html#vectors-and-data-frames"><i class="fa fa-check"></i><b>3.3</b> Vectors and Data frames</a><ul>
<li class="chapter" data-level="3.3.1" data-path="wrangling.html"><a href="wrangling.html#what-is-a-data-frame"><i class="fa fa-check"></i><b>3.3.1</b> What is a data frame?</a></li>
<li class="chapter" data-level="3.3.2" data-path="wrangling.html"><a href="wrangling.html#what-is-a-vector"><i class="fa fa-check"></i><b>3.3.2</b> What is a vector?</a></li>
<li class="chapter" data-level="3.3.3" data-path="wrangling.html"><a href="wrangling.html#how-are-vectors-different-from-a-list"><i class="fa fa-check"></i><b>3.3.3</b> How are vectors different from a list?</a></li>
<li class="chapter" data-level="3.3.4" data-path="wrangling.html"><a href="wrangling.html#what-does-this-have-to-do-with-data-frames"><i class="fa fa-check"></i><b>3.3.4</b> What does this have to do with data frames?</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="wrangling.html"><a href="wrangling.html#tidy-data"><i class="fa fa-check"></i><b>3.4</b> Tidy Data</a><ul>
<li class="chapter" data-level="3.4.1" data-path="wrangling.html"><a href="wrangling.html#what-is-tidy-data"><i class="fa fa-check"></i><b>3.4.1</b> What is tidy data?</a></li>
<li class="chapter" data-level="3.4.2" data-path="wrangling.html"><a href="wrangling.html#why-is-tidy-data-important-in-r"><i class="fa fa-check"></i><b>3.4.2</b> Why is tidy data important in R?</a></li>
<li class="chapter" data-level="3.4.3" data-path="wrangling.html"><a href="wrangling.html#going-from-wide-to-long-or-tidy-using-pivot_longer"><i class="fa fa-check"></i><b>3.4.3</b> Going from wide to long (or tidy!) using <code>pivot_longer</code></a></li>
<li class="chapter" data-level="3.4.4" data-path="wrangling.html"><a href="wrangling.html#going-from-long-to-wide-using-pivot_wider"><i class="fa fa-check"></i><b>3.4.4</b> Going from long to wide using <code>pivot_wider</code></a></li>
<li class="chapter" data-level="3.4.5" data-path="wrangling.html"><a href="wrangling.html#using-separate-to-deal-with-multiple-delimiters"><i class="fa fa-check"></i><b>3.4.5</b> Using <code>separate</code> to deal with multiple delimiters</a></li>
<li class="chapter" data-level="3.4.6" data-path="wrangling.html"><a href="wrangling.html#notes-on-defining-tidy-data"><i class="fa fa-check"></i><b>3.4.6</b> Notes on defining tidy data</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="wrangling.html"><a href="wrangling.html#combining-functions-using-the-pipe-operator"><i class="fa fa-check"></i><b>3.5</b> Combining functions using the pipe operator, <code>%&gt;%</code>:</a><ul>
<li class="chapter" data-level="3.5.1" data-path="wrangling.html"><a href="wrangling.html#using-to-combine-filter-and-select"><i class="fa fa-check"></i><b>3.5.1</b> Using <code>%&gt;%</code> to combine <code>filter</code> and <code>select</code></a></li>
<li class="chapter" data-level="3.5.2" data-path="wrangling.html"><a href="wrangling.html#using-with-more-than-two-functions"><i class="fa fa-check"></i><b>3.5.2</b> Using <code>%&gt;%</code> with more than two functions</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="wrangling.html"><a href="wrangling.html#iterating-over-data-with-group_by-summarize"><i class="fa fa-check"></i><b>3.6</b> Iterating over data with <code>group_by</code> + <code>summarize</code></a><ul>
<li class="chapter" data-level="3.6.1" data-path="wrangling.html"><a href="wrangling.html#calculating-summary-statistics"><i class="fa fa-check"></i><b>3.6.1</b> Calculating summary statistics:</a></li>
<li class="chapter" data-level="3.6.2" data-path="wrangling.html"><a href="wrangling.html#calculating-group-summary-statistics"><i class="fa fa-check"></i><b>3.6.2</b> Calculating group summary statistics:</a></li>
<li class="chapter" data-level="3.6.3" data-path="wrangling.html"><a href="wrangling.html#additional-reading-on-the-dplyr-functions"><i class="fa fa-check"></i><b>3.6.3</b> Additional reading on the <code>dplyr</code> functions</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="wrangling.html"><a href="wrangling.html#using-purrrs-map-functions-to-iterate"><i class="fa fa-check"></i><b>3.7</b> Using <code>purrr</code>’s <code>map*</code> functions to iterate</a></li>
<li class="chapter" data-level="3.8" data-path="wrangling.html"><a href="wrangling.html#additional-resources-1"><i class="fa fa-check"></i><b>3.8</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="viz.html"><a href="viz.html"><i class="fa fa-check"></i><b>4</b> Effective data visualization</a><ul>
<li class="chapter" data-level="4.1" data-path="viz.html"><a href="viz.html#overview-2"><i class="fa fa-check"></i><b>4.1</b> Overview</a></li>
<li class="chapter" data-level="4.2" data-path="viz.html"><a href="viz.html#chapter-learning-objectives-3"><i class="fa fa-check"></i><b>4.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="4.3" data-path="viz.html"><a href="viz.html#choosing-the-visualization"><i class="fa fa-check"></i><b>4.3</b> Choosing the visualization</a></li>
<li class="chapter" data-level="4.4" data-path="viz.html"><a href="viz.html#refining-the-visualization"><i class="fa fa-check"></i><b>4.4</b> Refining the visualization</a></li>
<li class="chapter" data-level="4.5" data-path="viz.html"><a href="viz.html#creating-visualizations-with-ggplot2"><i class="fa fa-check"></i><b>4.5</b> Creating visualizations with <code>ggplot2</code></a><ul>
<li class="chapter" data-level="4.5.1" data-path="viz.html"><a href="viz.html#the-mauna-loa-co2-data-set"><i class="fa fa-check"></i><b>4.5.1</b> The Mauna Loa CO2 data set</a></li>
<li class="chapter" data-level="4.5.2" data-path="viz.html"><a href="viz.html#the-island-landmass-data-set"><i class="fa fa-check"></i><b>4.5.2</b> The island landmass data set</a></li>
<li class="chapter" data-level="4.5.3" data-path="viz.html"><a href="viz.html#the-old-faithful-eruptionwaiting-time-data-set"><i class="fa fa-check"></i><b>4.5.3</b> The Old Faithful eruption/waiting time data set</a></li>
<li class="chapter" data-level="4.5.4" data-path="viz.html"><a href="viz.html#the-michelson-speed-of-light-data-set"><i class="fa fa-check"></i><b>4.5.4</b> The Michelson speed of light data set</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="viz.html"><a href="viz.html#explaining-the-visualization"><i class="fa fa-check"></i><b>4.6</b> Explaining the visualization</a></li>
<li class="chapter" data-level="4.7" data-path="viz.html"><a href="viz.html#saving-the-visualization"><i class="fa fa-check"></i><b>4.7</b> Saving the visualization</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="classification.html"><a href="classification.html"><i class="fa fa-check"></i><b>5</b> Classification I: training &amp; predicting</a><ul>
<li class="chapter" data-level="5.1" data-path="classification.html"><a href="classification.html#overview-3"><i class="fa fa-check"></i><b>5.1</b> Overview</a></li>
<li class="chapter" data-level="5.2" data-path="classification.html"><a href="classification.html#chapter-learning-objectives-4"><i class="fa fa-check"></i><b>5.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="5.3" data-path="classification.html"><a href="classification.html#the-classification-problem"><i class="fa fa-check"></i><b>5.3</b> The classification problem</a></li>
<li class="chapter" data-level="5.4" data-path="classification.html"><a href="classification.html#exploring-a-labelled-data-set"><i class="fa fa-check"></i><b>5.4</b> Exploring a labelled data set</a></li>
<li class="chapter" data-level="5.5" data-path="classification.html"><a href="classification.html#classification-with-k-nearest-neighbours"><i class="fa fa-check"></i><b>5.5</b> Classification with K-nearest neighbours</a></li>
<li class="chapter" data-level="5.6" data-path="classification.html"><a href="classification.html#k-nearest-neighbours-with-tidymodels"><i class="fa fa-check"></i><b>5.6</b> K-nearest neighbours with <code>tidymodels</code></a></li>
<li class="chapter" data-level="5.7" data-path="classification.html"><a href="classification.html#data-preprocessing-with-tidymodels"><i class="fa fa-check"></i><b>5.7</b> Data preprocessing with <code>tidymodels</code></a><ul>
<li class="chapter" data-level="5.7.1" data-path="classification.html"><a href="classification.html#centering-and-scaling"><i class="fa fa-check"></i><b>5.7.1</b> Centering and scaling</a></li>
<li class="chapter" data-level="5.7.2" data-path="classification.html"><a href="classification.html#balancing"><i class="fa fa-check"></i><b>5.7.2</b> Balancing</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="classification.html"><a href="classification.html#putting-it-together-in-a-workflow"><i class="fa fa-check"></i><b>5.8</b> Putting it together in a <code>workflow</code></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="classification-continued.html"><a href="classification-continued.html"><i class="fa fa-check"></i><b>6</b> Classification II: evaluation &amp; tuning</a><ul>
<li class="chapter" data-level="6.1" data-path="classification-continued.html"><a href="classification-continued.html#overview-4"><i class="fa fa-check"></i><b>6.1</b> Overview</a></li>
<li class="chapter" data-level="6.2" data-path="classification-continued.html"><a href="classification-continued.html#chapter-learning-objectives-5"><i class="fa fa-check"></i><b>6.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="6.3" data-path="classification-continued.html"><a href="classification-continued.html#evaluating-accuracy"><i class="fa fa-check"></i><b>6.3</b> Evaluating accuracy</a></li>
<li class="chapter" data-level="6.4" data-path="classification-continued.html"><a href="classification-continued.html#tuning-the-classifier"><i class="fa fa-check"></i><b>6.4</b> Tuning the classifier</a><ul>
<li class="chapter" data-level="6.4.1" data-path="classification-continued.html"><a href="classification-continued.html#cross-validation"><i class="fa fa-check"></i><b>6.4.1</b> Cross-validation</a></li>
<li class="chapter" data-level="6.4.2" data-path="classification-continued.html"><a href="classification-continued.html#parameter-value-selection"><i class="fa fa-check"></i><b>6.4.2</b> Parameter value selection</a></li>
<li class="chapter" data-level="6.4.3" data-path="classification-continued.html"><a href="classification-continued.html#underoverfitting"><i class="fa fa-check"></i><b>6.4.3</b> Under/overfitting</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="classification-continued.html"><a href="classification-continued.html#splitting-data"><i class="fa fa-check"></i><b>6.5</b> Splitting data</a></li>
<li class="chapter" data-level="6.6" data-path="classification-continued.html"><a href="classification-continued.html#summary"><i class="fa fa-check"></i><b>6.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="regression1.html"><a href="regression1.html"><i class="fa fa-check"></i><b>7</b> Regression I: K-nearest neighbours</a><ul>
<li class="chapter" data-level="7.1" data-path="regression1.html"><a href="regression1.html#overview-5"><i class="fa fa-check"></i><b>7.1</b> Overview</a></li>
<li class="chapter" data-level="7.2" data-path="regression1.html"><a href="regression1.html#chapter-learning-objectives-6"><i class="fa fa-check"></i><b>7.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="7.3" data-path="regression1.html"><a href="regression1.html#regression"><i class="fa fa-check"></i><b>7.3</b> Regression</a></li>
<li class="chapter" data-level="7.4" data-path="regression1.html"><a href="regression1.html#sacremento-real-estate-example"><i class="fa fa-check"></i><b>7.4</b> Sacremento real estate example</a></li>
<li class="chapter" data-level="7.5" data-path="regression1.html"><a href="regression1.html#k-nearest-neighbours-regression"><i class="fa fa-check"></i><b>7.5</b> K-nearest neighbours regression</a></li>
<li class="chapter" data-level="7.6" data-path="regression1.html"><a href="regression1.html#training-evaluating-and-tuning-the-model"><i class="fa fa-check"></i><b>7.6</b> Training, evaluating, and tuning the model</a></li>
<li class="chapter" data-level="7.7" data-path="regression1.html"><a href="regression1.html#underfitting-and-overfitting"><i class="fa fa-check"></i><b>7.7</b> Underfitting and overfitting</a></li>
<li class="chapter" data-level="7.8" data-path="regression1.html"><a href="regression1.html#evaluating-on-the-test-set"><i class="fa fa-check"></i><b>7.8</b> Evaluating on the test set</a></li>
<li class="chapter" data-level="7.9" data-path="regression1.html"><a href="regression1.html#strengths-and-limitations-of-k-nn-regression"><i class="fa fa-check"></i><b>7.9</b> Strengths and limitations of K-NN regression</a></li>
<li class="chapter" data-level="7.10" data-path="regression1.html"><a href="regression1.html#multivariate-k-nn-regression"><i class="fa fa-check"></i><b>7.10</b> Multivariate K-NN regression</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="regression2.html"><a href="regression2.html"><i class="fa fa-check"></i><b>8</b> Regression II: linear regression</a><ul>
<li class="chapter" data-level="8.1" data-path="regression2.html"><a href="regression2.html#overview-6"><i class="fa fa-check"></i><b>8.1</b> Overview</a></li>
<li class="chapter" data-level="8.2" data-path="regression2.html"><a href="regression2.html#chapter-learning-objectives-7"><i class="fa fa-check"></i><b>8.2</b> Chapter learning objectives</a></li>
<li class="chapter" data-level="8.3" data-path="regression2.html"><a href="regression2.html#simple-linear-regression"><i class="fa fa-check"></i><b>8.3</b> Simple linear regression</a></li>
<li class="chapter" data-level="8.4" data-path="regression2.html"><a href="regression2.html#linear-regression-in-r"><i class="fa fa-check"></i><b>8.4</b> Linear regression in R</a></li>
<li class="chapter" data-level="8.5" data-path="regression2.html"><a href="regression2.html#comparing-simple-linear-and-k-nn-regression"><i class="fa fa-check"></i><b>8.5</b> Comparing simple linear and K-NN regression</a></li>
<li class="chapter" data-level="8.6" data-path="regression2.html"><a href="regression2.html#multivariate-linear-regression"><i class="fa fa-check"></i><b>8.6</b> Multivariate linear regression</a></li>
<li class="chapter" data-level="8.7" data-path="regression2.html"><a href="regression2.html#the-other-side-of-regression"><i class="fa fa-check"></i><b>8.7</b> The other side of regression</a></li>
<li class="chapter" data-level="8.8" data-path="regression2.html"><a href="regression2.html#additional-resources-2"><i class="fa fa-check"></i><b>8.8</b> Additional resources</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Science: A First Introduction</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regression1" class="section level1">
<h1><span class="header-section-number">Chapter 7</span> Regression I: K-nearest neighbours</h1>
<div id="overview-5" class="section level2">
<h2><span class="header-section-number">7.1</span> Overview</h2>
<p>This chapter will provide an introduction to regression through K-nearest
neighbours (K-NN) in a predictive context, focusing primarily on the case where
there is a single predictor and single response variable of interest. The
chapter concludes with an example of K-nearest neighbours regression with
multiple predictors.</p>
</div>
<div id="chapter-learning-objectives-6" class="section level2">
<h2><span class="header-section-number">7.2</span> Chapter learning objectives</h2>
<p>By the end of the chapter, students will be able to:</p>
<ul>
<li>Recognize situations where a simple regression analysis would be appropriate for making predictions.</li>
<li>Explain the K-nearest neighbour (K-NN) regression algorithm and describe how it differs from K-NN classification.</li>
<li>Interpret the output of a K-NN regression.</li>
<li>In a dataset with two or more variables, perform K-nearest neighbour regression in R using a <code>tidymodels</code> workflow</li>
<li>Execute cross-validation in R to choose the number of neighbours.</li>
<li>Evaluate K-NN regression prediction accuracy in R using a test data set and an appropriate metric (<em>e.g.</em>, root means square prediction error).</li>
<li>In the context of K-NN regression, compare and contrast goodness of fit and prediction properties (namely RMSE vs RMSPE).</li>
<li>Describe advantages and disadvantages of the K-nearest neighbour regression approach.</li>
</ul>
</div>
<div id="regression" class="section level2">
<h2><span class="header-section-number">7.3</span> Regression</h2>
<p>Regression, like classification, is a predictive problem setting where we want
to use past information to predict future observations. But in the case of
regression, the goal is to predict numerical values instead of class labels.
For example, we could try to use the number of hours a person spends on
exercise each week to predict whether they would qualify for the annual Boston
marathon (<em>classification</em>) or to predict their race time itself
(<em>regression</em>). As another example, we could try to use the size of a house to
predict whether it sold for more than $500,000 (<em>classification</em>) or to
predict its sale price itself (<em>regression</em>). We will use K-nearest neighbours
to explore this question in the rest of this chapter, using a real estate data
set from Sacremento, California.</p>
</div>
<div id="sacremento-real-estate-example" class="section level2">
<h2><span class="header-section-number">7.4</span> Sacremento real estate example</h2>
<p>Let’s start by loading the packages we need and doing some preliminary
exploratory analysis. The Sacramento real estate data set we will study in this chapter
was <a href="https://support.spatialkey.com/spatialkey-sample-csv-data/">originally reported in the Sacramento Bee</a>,
but we have provided it with this repository as a stable source for the data.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="regression1.html#cb1-1"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="regression1.html#cb1-2"></a><span class="kw">library</span>(tidymodels)</span>
<span id="cb1-3"><a href="regression1.html#cb1-3"></a><span class="kw">library</span>(gridExtra)</span>
<span id="cb1-4"><a href="regression1.html#cb1-4"></a></span>
<span id="cb1-5"><a href="regression1.html#cb1-5"></a>sacramento &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;data/sacramento.csv&quot;</span>)</span>
<span id="cb1-6"><a href="regression1.html#cb1-6"></a>sacramento</span></code></pre></div>
<pre><code>## # A tibble: 932 x 9
##    city           zip     beds baths  sqft type        price latitude longitude
##    &lt;chr&gt;          &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;       &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
##  1 SACRAMENTO     z95838     2     1   836 Residential 59222     38.6     -121.
##  2 SACRAMENTO     z95823     3     1  1167 Residential 68212     38.5     -121.
##  3 SACRAMENTO     z95815     2     1   796 Residential 68880     38.6     -121.
##  4 SACRAMENTO     z95815     2     1   852 Residential 69307     38.6     -121.
##  5 SACRAMENTO     z95824     2     1   797 Residential 81900     38.5     -121.
##  6 SACRAMENTO     z95841     3     1  1122 Condo       89921     38.7     -121.
##  7 SACRAMENTO     z95842     3     2  1104 Residential 90895     38.7     -121.
##  8 SACRAMENTO     z95820     3     1  1177 Residential 91002     38.5     -121.
##  9 RANCHO_CORDOVA z95670     2     2   941 Condo       94905     38.6     -121.
## 10 RIO_LINDA      z95673     3     2  1146 Residential 98937     38.7     -121.
## # … with 922 more rows</code></pre>
<p>The purpose of this exercise is to understand whether we can we use house size
to predict house sale price in the Sacramento, CA area. The columns in this
data that we are interested in are <code>sqft</code> (house size, in livable square feet)
and <code>price</code> (house price, in US dollars (USD). The first step is to visualize
the data as a scatter plot where we place the predictor/explanatory variable
(house size) on the x-axis, and we place the target/response variable that we
want to predict (price) on the y-axis:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="regression1.html#cb3-1"></a>eda &lt;-<span class="st"> </span><span class="kw">ggplot</span>(sacramento, <span class="kw">aes</span>(<span class="dt">x =</span> sqft, <span class="dt">y =</span> price)) <span class="op">+</span></span>
<span id="cb3-2"><a href="regression1.html#cb3-2"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.4</span>) <span class="op">+</span></span>
<span id="cb3-3"><a href="regression1.html#cb3-3"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;House size (square footage)&quot;</span>) <span class="op">+</span></span>
<span id="cb3-4"><a href="regression1.html#cb3-4"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Price (USD)&quot;</span>) <span class="op">+</span></span>
<span id="cb3-5"><a href="regression1.html#cb3-5"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">labels =</span> <span class="kw">dollar_format</span>())</span>
<span id="cb3-6"><a href="regression1.html#cb3-6"></a>eda</span></code></pre></div>
<div class="figure"><span id="fig:07-edaRegr"></span>
<img src="bookdown_files/figure-html/07-edaRegr-1.png" alt="Scatter plot of price (USD) versus house size (square footage)" width="480" />
<p class="caption">
FIGURE 7.1: Scatter plot of price (USD) versus house size (square footage)
</p>
</div>
<p>Based on the visualization above, we can see that in Sacramento, CA, as the
size of a house increases, so does its sale price. Thus, we can reason that we
may be able to use the size of a not-yet-sold house (for which we don’t know
the sale price) to predict its final sale price.</p>
</div>
<div id="k-nearest-neighbours-regression" class="section level2">
<h2><span class="header-section-number">7.5</span> K-nearest neighbours regression</h2>
<p>Much like in the case of classification, we can use a K-nearest
neighbours-based approach in regression to make predictions. Let’s take a small
sample of the data above and walk through how K-nearest neighbours (knn) works
in a regression context before we dive in to creating our model and assessing
how well it predicts house price. This subsample is taken to allow us to
illustrate the mechanics of K-NN regression with a few data points; later in
this chapter we will use all the data.</p>
<p>To take a small random sample of size 30, we’ll use the function <code>sample_n</code>.
This function takes two arguments:</p>
<ol style="list-style-type: decimal">
<li><code>tbl</code> (a data frame-like object to sample from)</li>
<li><code>size</code> (the number of observations/rows to be randomly selected/sampled)</li>
</ol>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="regression1.html#cb4-1"></a><span class="kw">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb4-2"><a href="regression1.html#cb4-2"></a>small_sacramento &lt;-<span class="st"> </span><span class="kw">sample_n</span>(sacramento, <span class="dt">size =</span> <span class="dv">30</span>)</span></code></pre></div>
<p>Next let’s say we come across a 2,000 square-foot house in Sacramento we are
interested in purchasing, with an advertised list price of $350,000. Should we
offer to pay the asking price for this house, or is it overpriced and we should
offer less? Absent any other information, we can get a sense for a good answer
to this question by using the data we have to predict the sale price given the
sale prices we have already observed. But in the plot below, we have no
observations of a house of size <em>exactly</em> 2000 square feet. How can we predict
the price?</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="regression1.html#cb5-1"></a>small_plot &lt;-<span class="st"> </span><span class="kw">ggplot</span>(small_sacramento, <span class="kw">aes</span>(<span class="dt">x =</span> sqft, <span class="dt">y =</span> price)) <span class="op">+</span></span>
<span id="cb5-2"><a href="regression1.html#cb5-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb5-3"><a href="regression1.html#cb5-3"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;House size (square footage)&quot;</span>) <span class="op">+</span></span>
<span id="cb5-4"><a href="regression1.html#cb5-4"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Price (USD)&quot;</span>) <span class="op">+</span></span>
<span id="cb5-5"><a href="regression1.html#cb5-5"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">labels =</span> <span class="kw">dollar_format</span>()) <span class="op">+</span></span>
<span id="cb5-6"><a href="regression1.html#cb5-6"></a><span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="dv">2000</span>, <span class="dt">linetype =</span> <span class="st">&quot;dotted&quot;</span>)</span>
<span id="cb5-7"><a href="regression1.html#cb5-7"></a>small_plot</span></code></pre></div>
<div class="figure"><span id="fig:07-small-eda-regr"></span>
<img src="bookdown_files/figure-html/07-small-eda-regr-1.png" alt="Scatter plot of price (USD) versus house size (square footage) with vertical line indicating 2000 square feet on x-axis" width="480" />
<p class="caption">
FIGURE 7.2: Scatter plot of price (USD) versus house size (square footage) with vertical line indicating 2000 square feet on x-axis
</p>
</div>
<p>We will employ the same intuition from the classification chapter, and use the
neighbouring points to the new point of interest to suggest/predict what its
price should be. For the example above, we find and label the 5 nearest
neighbours to our observation of a house that is 2000 square feet:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="regression1.html#cb6-1"></a>nearest_neighbours &lt;-<span class="st"> </span>small_sacramento <span class="op">%&gt;%</span></span>
<span id="cb6-2"><a href="regression1.html#cb6-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">diff =</span> <span class="kw">abs</span>(<span class="dv">2000</span> <span class="op">-</span><span class="st"> </span>sqft)) <span class="op">%&gt;%</span></span>
<span id="cb6-3"><a href="regression1.html#cb6-3"></a><span class="st">  </span><span class="kw">arrange</span>(diff) <span class="op">%&gt;%</span></span>
<span id="cb6-4"><a href="regression1.html#cb6-4"></a><span class="st">  </span><span class="kw">slice</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>) <span class="co">#subset the first 5 rows</span></span>
<span id="cb6-5"><a href="regression1.html#cb6-5"></a>nearest_neighbours</span></code></pre></div>
<pre><code>## # A tibble: 5 x 10
##   city         zip    beds baths  sqft type       price latitude longitude  diff
##   &lt;chr&gt;        &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;
## 1 GOLD_RIVER   z956…     3     2  1981 Resident… 305000     38.6     -121.    19
## 2 ELK_GROVE    z957…     4     2  2056 Resident… 275000     38.4     -121.    56
## 3 ELK_GROVE    z956…     5     3  2136 Resident… 223058     38.4     -121.   136
## 4 RANCHO_CORD… z957…     4     2  1713 Resident… 263500     38.6     -121.   287
## 5 RIO_LINDA    z956…     2     2  1690 Resident… 136500     38.7     -121.   310</code></pre>
<div class="figure"><span id="fig:07-knn3-example"></span>
<img src="bookdown_files/figure-html/07-knn3-example-1.png" alt="Scatter plot of price (USD) versus house size (square footage) with lines to 5 nearest neighbours" width="480" />
<p class="caption">
FIGURE 7.3: Scatter plot of price (USD) versus house size (square footage) with lines to 5 nearest neighbours
</p>
</div>
<p>Now that we have the 5 nearest neighbours (in terms of house size) to our new
2,000 square-foot house of interest, we can use their values to predict a
selling price for the new home. Specifically, we can take the mean (or
average) of these 5 values as our predicted value.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="regression1.html#cb8-1"></a>prediction &lt;-<span class="st"> </span>nearest_neighbours <span class="op">%&gt;%</span></span>
<span id="cb8-2"><a href="regression1.html#cb8-2"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">predicted =</span> <span class="kw">mean</span>(price))</span>
<span id="cb8-3"><a href="regression1.html#cb8-3"></a>prediction</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   predicted
##       &lt;dbl&gt;
## 1   240612.</code></pre>
<div class="figure"><span id="fig:07-predictedViz-knn"></span>
<img src="bookdown_files/figure-html/07-predictedViz-knn-1.png" alt="Scatter plot of price (USD) versus house size (square footage) with predicted price for a 2000 square-foot house based on 5 nearest neighbours represented as a red dot" width="480" />
<p class="caption">
FIGURE 7.4: Scatter plot of price (USD) versus house size (square footage) with predicted price for a 2000 square-foot house based on 5 nearest neighbours represented as a red dot
</p>
</div>
<p>Our predicted price is $240612
(shown as a red point above), which is much less than $350,000; perhaps we
might want to offer less than the list price at which the house is advertised.
But this is only the very beginning of the story. We still have all the same
unanswered questions here with K-NN regression that we had with K-NN
classification: which <span class="math inline">\(K\)</span> do we choose, and is our model any good at making
predictions? In the next few sections, we will address these questions in the
context of K-NN regression.</p>
</div>
<div id="training-evaluating-and-tuning-the-model" class="section level2">
<h2><span class="header-section-number">7.6</span> Training, evaluating, and tuning the model</h2>
<p>As usual, we must start by putting some test data away in a lock box that we
will come back to only after we choose our final model. Let’s take care of that
now. Note that for the remainder of the chapter we’ll be working with the
entire Sacramento data set, as opposed to the smaller sample of 30 points above.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="regression1.html#cb10-1"></a><span class="kw">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb10-2"><a href="regression1.html#cb10-2"></a>sacramento_split &lt;-<span class="st"> </span><span class="kw">initial_split</span>(sacramento, <span class="dt">prop =</span> <span class="fl">0.6</span>, <span class="dt">strata =</span> price)</span>
<span id="cb10-3"><a href="regression1.html#cb10-3"></a>sacramento_train &lt;-<span class="st"> </span><span class="kw">training</span>(sacramento_split)</span>
<span id="cb10-4"><a href="regression1.html#cb10-4"></a>sacramento_test &lt;-<span class="st"> </span><span class="kw">testing</span>(sacramento_split)</span></code></pre></div>
<p>Next, we’ll use cross-validation to choose <span class="math inline">\(K\)</span>. In K-NN classification, we used
accuracy to see how well our predictions matched the true labels. Here in the
context of K-NN regression we will use root mean square prediction error
(RMSPE) instead. The mathematical formula for calculating RMSPE is:</p>
<p><span class="math display">\[\text{RMSPE} = \sqrt{\frac{1}{n}\sum\limits_{i=1}^{n}(y_i - \hat{y}_i)^2}\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(n\)</span> is the number of observations</li>
<li><span class="math inline">\(y_i\)</span> is the observed value for the <span class="math inline">\(i^\text{th}\)</span> observation</li>
<li><span class="math inline">\(\hat{y}_i\)</span> is the forcasted/predicted value for the <span class="math inline">\(i^\text{th}\)</span> observation</li>
</ul>
<p>A key feature of the formula for RMPSE is the squared difference between the observed
target/response variable value, <span class="math inline">\(y\)</span>, and the prediction target/response
variable value, <span class="math inline">\(\hat{y}_i\)</span>, for each observation (from 1 to <span class="math inline">\(i\)</span>).
If the predictions are very close to the true values, then
RMSPE will be small. If, on the other-hand, the predictions are very
different to the true values, then RMSPE will be quite large. When we
use cross validation, we will choose the <span class="math inline">\(K\)</span> that gives
us the smallest RMSPE.</p>
<blockquote>
<p><strong>RMSPE versus RMSE</strong>
When using many code packages (<code>tidymodels</code> included), the evaluation output
we will get to assess the prediction quality of
our K-NN regression models is labelled “RMSE”, or “root mean squared
error”. Why is this so, and why not just RMSPE?
In statistics, we try to be very precise with our
language to indicate whether we are calculating the prediction error on the
training data (<em>in-sample</em> prediction) versus on the testing data
(<em>out-of-sample</em> prediction). When predicting and evaluating prediction quality on the training data, we
say RMSE. By contrast, when predicting and evaluating prediction quality
on the testing or validation data, we say RMSPE.
The equation for calculating RMSE and RMSPE is exactly the same; all that changes is whether the <span class="math inline">\(y\)</span>s are
training or testing data. But many people just use RMSE for both,
and rely on context to denote which data the root mean squared error is being calculated on.</p>
</blockquote>
<p>Now that we know how we can assess how well our model predicts a numerical
value, let’s use R to perform cross-validation and to choose the optimal <span class="math inline">\(K\)</span>.
First, we will create a model specification for K-nearest neighbours regression,
as well as a recipe for preprocessing our data. Note that we use <code>set_mode("regression")</code>
now in the model specification to denote a regression problem, as opposed to the classification
problems from the previous chapters. Note also that we include standardization
in our preprocessing to build good habits, but since we only have one
predictor it is technically not necessary; there is no risk of comparing two predictors
of different scales.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="regression1.html#cb11-1"></a>sacr_recipe &lt;-<span class="st"> </span><span class="kw">recipe</span>(price <span class="op">~</span><span class="st"> </span>sqft, <span class="dt">data =</span> sacramento_train) <span class="op">%&gt;%</span></span>
<span id="cb11-2"><a href="regression1.html#cb11-2"></a><span class="st">  </span><span class="kw">step_scale</span>(<span class="kw">all_predictors</span>()) <span class="op">%&gt;%</span></span>
<span id="cb11-3"><a href="regression1.html#cb11-3"></a><span class="st">  </span><span class="kw">step_center</span>(<span class="kw">all_predictors</span>())</span>
<span id="cb11-4"><a href="regression1.html#cb11-4"></a></span>
<span id="cb11-5"><a href="regression1.html#cb11-5"></a>sacr_spec &lt;-<span class="st"> </span><span class="kw">nearest_neighbor</span>(<span class="dt">weight_func =</span> <span class="st">&quot;rectangular&quot;</span>, <span class="dt">neighbors =</span> <span class="kw">tune</span>()) <span class="op">%&gt;%</span></span>
<span id="cb11-6"><a href="regression1.html#cb11-6"></a><span class="st">  </span><span class="kw">set_engine</span>(<span class="st">&quot;kknn&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb11-7"><a href="regression1.html#cb11-7"></a><span class="st">  </span><span class="kw">set_mode</span>(<span class="st">&quot;regression&quot;</span>)</span>
<span id="cb11-8"><a href="regression1.html#cb11-8"></a></span>
<span id="cb11-9"><a href="regression1.html#cb11-9"></a>sacr_vfold &lt;-<span class="st"> </span><span class="kw">vfold_cv</span>(sacramento_train, <span class="dt">v =</span> <span class="dv">5</span>, <span class="dt">strata =</span> price)</span>
<span id="cb11-10"><a href="regression1.html#cb11-10"></a></span>
<span id="cb11-11"><a href="regression1.html#cb11-11"></a>sacr_wkflw &lt;-<span class="st"> </span><span class="kw">workflow</span>() <span class="op">%&gt;%</span></span>
<span id="cb11-12"><a href="regression1.html#cb11-12"></a><span class="st">  </span><span class="kw">add_recipe</span>(sacr_recipe) <span class="op">%&gt;%</span></span>
<span id="cb11-13"><a href="regression1.html#cb11-13"></a><span class="st">  </span><span class="kw">add_model</span>(sacr_spec)</span>
<span id="cb11-14"><a href="regression1.html#cb11-14"></a>sacr_wkflw</span></code></pre></div>
<pre><code>## ══ Workflow ════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
## Preprocessor: Recipe
## Model: nearest_neighbor()
## 
## ── Preprocessor ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## 2 Recipe Steps
## 
## ● step_scale()
## ● step_center()
## 
## ── Model ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
## K-Nearest Neighbor Model Specification (regression)
## 
## Main Arguments:
##   neighbors = tune()
##   weight_func = rectangular
## 
## Computational engine: kknn</code></pre>
<p>The major difference you can see in the above workflow compared to previous
chapters is that we are running regression rather than classification. The fact
that we use <code>set_mode("regression")</code> essentially
tells <code>tidymodels</code> that we need to use different metrics (RMSPE, not accuracy)
for tuning and evaluation. You can see this in the following code, which tunes
the model and returns the RMSPE for each number of neighbours.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="regression1.html#cb13-1"></a>gridvals &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">neighbors =</span> <span class="kw">seq</span>(<span class="dv">1</span>, <span class="dv">200</span>))</span>
<span id="cb13-2"><a href="regression1.html#cb13-2"></a></span>
<span id="cb13-3"><a href="regression1.html#cb13-3"></a>sacr_results &lt;-<span class="st"> </span>sacr_wkflw <span class="op">%&gt;%</span></span>
<span id="cb13-4"><a href="regression1.html#cb13-4"></a><span class="st">  </span><span class="kw">tune_grid</span>(<span class="dt">resamples =</span> sacr_vfold, <span class="dt">grid =</span> gridvals) <span class="op">%&gt;%</span></span>
<span id="cb13-5"><a href="regression1.html#cb13-5"></a><span class="st">  </span><span class="kw">collect_metrics</span>()</span>
<span id="cb13-6"><a href="regression1.html#cb13-6"></a></span>
<span id="cb13-7"><a href="regression1.html#cb13-7"></a><span class="co"># show all the results</span></span>
<span id="cb13-8"><a href="regression1.html#cb13-8"></a>sacr_results</span></code></pre></div>
<pre><code>## # A tibble: 400 x 6
##    neighbors .metric .estimator       mean     n   std_err
##        &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;           &lt;dbl&gt; &lt;int&gt;     &lt;dbl&gt;
##  1         1 rmse    standard   116654.        5 7186.    
##  2         1 rsq     standard        0.372     5    0.0463
##  3         2 rmse    standard   101103.        5 5872.    
##  4         2 rsq     standard        0.453     5    0.0386
##  5         3 rmse    standard    96708.        5 4211.    
##  6         3 rsq     standard        0.483     5    0.0277
##  7         4 rmse    standard    93927.        5 3502.    
##  8         4 rsq     standard        0.503     5    0.0298
##  9         5 rmse    standard    89642.        5 3768.    
## 10         5 rsq     standard        0.543     5    0.0303
## # … with 390 more rows</code></pre>
<p>We take the <em>minimum</em> RMSPE to find the best setting for the number of neighbours:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="regression1.html#cb15-1"></a><span class="co"># show only the row of minimum RMSPE</span></span>
<span id="cb15-2"><a href="regression1.html#cb15-2"></a>sacr_min &lt;-<span class="st"> </span>sacr_results <span class="op">%&gt;%</span></span>
<span id="cb15-3"><a href="regression1.html#cb15-3"></a><span class="st">  </span><span class="kw">filter</span>(.metric <span class="op">==</span><span class="st"> &quot;rmse&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb15-4"><a href="regression1.html#cb15-4"></a><span class="st">  </span><span class="kw">filter</span>(mean <span class="op">==</span><span class="st"> </span><span class="kw">min</span>(mean))</span>
<span id="cb15-5"><a href="regression1.html#cb15-5"></a>sacr_min</span></code></pre></div>
<pre><code>## # A tibble: 1 x 6
##   neighbors .metric .estimator   mean     n std_err
##       &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;       &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt;
## 1        14 rmse    standard   84356.     5   4050.</code></pre>
<p>Here we can see that the smallest RMSPE occurs when <span class="math inline">\(K =\)</span> 14.</p>
</div>
<div id="underfitting-and-overfitting" class="section level2">
<h2><span class="header-section-number">7.7</span> Underfitting and overfitting</h2>
<p>Similar to the setting of classification, by setting the number of neighbours
to be too small or too large, we cause the RMSPE to increase:</p>
<div class="figure"><span id="fig:07-choose-k-knn-plot"></span>
<img src="bookdown_files/figure-html/07-choose-k-knn-plot-1.png" alt="Effect of the number of neighbours on the RMSPE" width="480" />
<p class="caption">
FIGURE 7.5: Effect of the number of neighbours on the RMSPE
</p>
</div>
<p>What is happening here? To visualize the effect of different settings of <span class="math inline">\(K\)</span> on the
regression model, we will plot the predicted values for house price from
our K-NN regression models for 6 different values for <span class="math inline">\(K\)</span>. For each model, we
predict a price for every possible home size across the range of home sizes we
observed in the data set (here 500 to 4250 square feet) and we plot the
predicted prices as a blue line:</p>
<div class="figure"><span id="fig:07-howK"></span>
<img src="bookdown_files/figure-html/07-howK-1.png" alt="Predicted values for house price (represented as a blue line) from K-NN regression models for six different values for $K$" width="960" />
<p class="caption">
FIGURE 7.6: Predicted values for house price (represented as a blue line) from K-NN regression models for six different values for <span class="math inline">\(K\)</span>
</p>
</div>
<p>Based on the plots above, we see that when <span class="math inline">\(K\)</span> = 1, the blue line runs perfectly
through almost all of our training observations. This happens because our
predicted values for a given region depend on just a single observation. A
model like this has high variance and low bias (intuitively, it provides unreliable
predictions). It has high variance because
the flexible blue line follows the training observations very closely, and if
we were to change any one of the training observation data points we would
change the flexible blue line quite a lot. This means that the blue line
matches the data we happen to have in this training data set, however, if we
were to collect another training data set from the Sacramento real estate
market it likely wouldn’t match those observations as well. Another term
that we use to collectively describe this phenomenon is <em>overfitting</em>.</p>
<p>What about the plot where <span class="math inline">\(K\)</span> is quite large, say <span class="math inline">\(K\)</span> = 450, for example? When
<span class="math inline">\(K\)</span> = 450 for this data set, the blue line is extremely smooth, and almost
flat. This happens because our predicted values for a given x value (here home
size), depend on many many (450) neighbouring observations. A model
like this has low variance and high bias (intuitively, it provides very reliable,
but generally very inaccurate predictions). It has low variance because the
smooth, inflexible blue line does not follow the training observations very
closely, and if we were to change any one of the training observation data
points it really wouldn’t affect the shape of the smooth blue line at all. This
means that although the blue line matches does not match the data we happen to
have in this particular training data set perfectly, if we were to collect
another training data set from the Sacramento real estate market it likely
would match those observations equally as well as it matches those in this
training data set. Another term that
we use to collectively describe this kind of model is <em>underfitting</em>.</p>
<p>Ideally, what we want is neither of the two situations discussed above. Instead,
we would like a model with low variance (so that it will transfer/generalize
well to other data sets, and isn’t too dependent on the
observations that happen to be in the training set) <strong>and</strong> low bias
(where the model does not completely ignore our training data). If we explore
the other values for <span class="math inline">\(K\)</span>, in particular <span class="math inline">\(K\)</span> = 14
(as suggested by cross-validation),
we can see it has a lower bias than our model with a very high <span class="math inline">\(K\)</span> (e.g., 450),
and thus the model/predicted values better match the actual observed values
than the high <span class="math inline">\(K\)</span> model. Additionally, it has lower variance than our model
with a very low <span class="math inline">\(K\)</span> (e.g., 1) and thus it should better transer/generalize to
other data sets compared to the low <span class="math inline">\(K\)</span> model. All of this is similar to how
the choice of <span class="math inline">\(K\)</span> affects K-NN classification (discussed in the previous
chapter).</p>
</div>
<div id="evaluating-on-the-test-set" class="section level2">
<h2><span class="header-section-number">7.8</span> Evaluating on the test set</h2>
<p>To assess how well our model might do at predicting on unseen data, we will
assess its RMSPE on the test data. To do this, we will first
re-train our K-NN regression model on the entire training data set,
using <span class="math inline">\(K =\)</span> 14 neighbours. Then we will
use <code>predict</code> to make predictions on the test data, and use the <code>metrics</code>
function again to compute the summary of regression quality. Because
we specify that we are performing regression in <code>set_mode</code>, the <code>metrics</code>
function knows to output a quality summary related to regression, and not, say, classification.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="regression1.html#cb17-1"></a><span class="kw">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb17-2"><a href="regression1.html#cb17-2"></a>kmin &lt;-<span class="st"> </span>sacr_min <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">pull</span>(neighbors)</span>
<span id="cb17-3"><a href="regression1.html#cb17-3"></a>sacr_spec &lt;-<span class="st"> </span><span class="kw">nearest_neighbor</span>(<span class="dt">weight_func =</span> <span class="st">&quot;rectangular&quot;</span>, <span class="dt">neighbors =</span> kmin) <span class="op">%&gt;%</span></span>
<span id="cb17-4"><a href="regression1.html#cb17-4"></a><span class="st">  </span><span class="kw">set_engine</span>(<span class="st">&quot;kknn&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb17-5"><a href="regression1.html#cb17-5"></a><span class="st">  </span><span class="kw">set_mode</span>(<span class="st">&quot;regression&quot;</span>)</span>
<span id="cb17-6"><a href="regression1.html#cb17-6"></a></span>
<span id="cb17-7"><a href="regression1.html#cb17-7"></a>sacr_fit &lt;-<span class="st"> </span><span class="kw">workflow</span>() <span class="op">%&gt;%</span></span>
<span id="cb17-8"><a href="regression1.html#cb17-8"></a><span class="st">  </span><span class="kw">add_recipe</span>(sacr_recipe) <span class="op">%&gt;%</span></span>
<span id="cb17-9"><a href="regression1.html#cb17-9"></a><span class="st">  </span><span class="kw">add_model</span>(sacr_spec) <span class="op">%&gt;%</span></span>
<span id="cb17-10"><a href="regression1.html#cb17-10"></a><span class="st">  </span><span class="kw">fit</span>(<span class="dt">data =</span> sacramento_train)</span>
<span id="cb17-11"><a href="regression1.html#cb17-11"></a></span>
<span id="cb17-12"><a href="regression1.html#cb17-12"></a>sacr_summary &lt;-<span class="st"> </span>sacr_fit <span class="op">%&gt;%</span></span>
<span id="cb17-13"><a href="regression1.html#cb17-13"></a><span class="st">  </span><span class="kw">predict</span>(sacramento_test) <span class="op">%&gt;%</span></span>
<span id="cb17-14"><a href="regression1.html#cb17-14"></a><span class="st">  </span><span class="kw">bind_cols</span>(sacramento_test) <span class="op">%&gt;%</span></span>
<span id="cb17-15"><a href="regression1.html#cb17-15"></a><span class="st">  </span><span class="kw">metrics</span>(<span class="dt">truth =</span> price, <span class="dt">estimate =</span> .pred)</span>
<span id="cb17-16"><a href="regression1.html#cb17-16"></a></span>
<span id="cb17-17"><a href="regression1.html#cb17-17"></a>sacr_summary</span></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard   87737.   
## 2 rsq     standard       0.546
## 3 mae     standard   65400.</code></pre>
<p>Our final model’s test error as assessed by RMSPE
is 87737.
But what does this RMSPE score mean? When we calculated test set prediction accuracy in K-NN
classification, the highest possible value was 1 and the lowest possible value was 0.
If we got a value close to 1, our model was “good;” and otherwise,
the model was “not good.” What about RMSPE? Unfortunately there is no default scale
for RMSPE. Instead, it is measured in
the units of the target/response variable, and so it is a bit hard to
interpret. For now, let’s consider this approach to thinking about RMSPE from
our testing data set: as long as its not significantly worse than the cross-validation
RMSPE of our best model, then we can say that we’re not doing too much worse on
the test data than we did on the training data. So the model appears to be
generalizing well to a new data set it has never seen before. In future courses
on statistical/machine learning, you will learn more about how to interpret RMSPE
from testing data and other ways to assess models.</p>
<p>Finally, what does our model look like when we predict across all possible
house sizes we might encounter in the Sacramento area? We plotted it above
where we explored how <span class="math inline">\(k\)</span> affects K-NN regression, but we show it again now,
along with the code that generated it:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="regression1.html#cb19-1"></a><span class="kw">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb19-2"><a href="regression1.html#cb19-2"></a>sacr_preds &lt;-<span class="st"> </span>sacr_fit <span class="op">%&gt;%</span></span>
<span id="cb19-3"><a href="regression1.html#cb19-3"></a><span class="st">  </span><span class="kw">predict</span>(sacramento_train) <span class="op">%&gt;%</span></span>
<span id="cb19-4"><a href="regression1.html#cb19-4"></a><span class="st">  </span><span class="kw">bind_cols</span>(sacramento_train)</span>
<span id="cb19-5"><a href="regression1.html#cb19-5"></a></span>
<span id="cb19-6"><a href="regression1.html#cb19-6"></a>plot_final &lt;-<span class="st"> </span><span class="kw">ggplot</span>(sacr_preds, <span class="kw">aes</span>(<span class="dt">x =</span> sqft, <span class="dt">y =</span> price)) <span class="op">+</span></span>
<span id="cb19-7"><a href="regression1.html#cb19-7"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">alpha =</span> <span class="fl">0.4</span>) <span class="op">+</span></span>
<span id="cb19-8"><a href="regression1.html#cb19-8"></a><span class="st">  </span><span class="kw">xlab</span>(<span class="st">&quot;House size (square footage)&quot;</span>) <span class="op">+</span></span>
<span id="cb19-9"><a href="regression1.html#cb19-9"></a><span class="st">  </span><span class="kw">ylab</span>(<span class="st">&quot;Price (USD)&quot;</span>) <span class="op">+</span></span>
<span id="cb19-10"><a href="regression1.html#cb19-10"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">labels =</span> <span class="kw">dollar_format</span>()) <span class="op">+</span></span>
<span id="cb19-11"><a href="regression1.html#cb19-11"></a><span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">data =</span> sacr_preds, <span class="kw">aes</span>(<span class="dt">x =</span> sqft, <span class="dt">y =</span> .pred), <span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="op">+</span></span>
<span id="cb19-12"><a href="regression1.html#cb19-12"></a><span class="st">  </span><span class="kw">ggtitle</span>(<span class="kw">paste0</span>(<span class="st">&quot;K = &quot;</span>, kmin))</span>
<span id="cb19-13"><a href="regression1.html#cb19-13"></a></span>
<span id="cb19-14"><a href="regression1.html#cb19-14"></a>plot_final</span></code></pre></div>
<div class="figure"><span id="fig:07-predict-all"></span>
<img src="bookdown_files/figure-html/07-predict-all-1.png" alt="Predicted values for house price (represented as a blue line) for K-NN regression model with $K = 14$" width="480" />
<p class="caption">
FIGURE 7.7: Predicted values for house price (represented as a blue line) for K-NN regression model with <span class="math inline">\(K = 14\)</span>
</p>
</div>
</div>
<div id="strengths-and-limitations-of-k-nn-regression" class="section level2">
<h2><span class="header-section-number">7.9</span> Strengths and limitations of K-NN regression</h2>
<p>As with K-NN classification (or any prediction algorithm for that manner), K-NN regression has both strengths and weaknesses. Some are listed here:</p>
<p><strong>Strengths of K-NN regression</strong></p>
<ol style="list-style-type: decimal">
<li>Simple and easy to understand</li>
<li>No assumptions about what the data must look like</li>
<li>Works well with non-linear relationships (i.e., if the relationship is not a straight line)</li>
</ol>
<p><strong>Limitations of K-NN regression</strong></p>
<ol style="list-style-type: decimal">
<li>As data gets bigger and bigger, K-NN gets slower and slower, quite quickly 2. Does not perform well with a large number of predictors unless the size of the training set is exponentially larger</li>
<li>Does not predict well beyond the range of values input in your training data</li>
</ol>
</div>
<div id="multivariate-k-nn-regression" class="section level2">
<h2><span class="header-section-number">7.10</span> Multivariate K-NN regression</h2>
<p>As in K-NN classification, in K-NN regression we can have multiple predictors.
When we have multiple predictors in K-NN regression, we have the same concern
regarding the scale of the predictors. This is because once again,
predictions are made by identifying the <span class="math inline">\(K\)</span>
observations that are nearest to the new point we want to predict, and any
variables that are on a large scale will have a much larger effect than
variables on a small scale. Since the <code>recipe</code> we built above scales and centers
all predictor variables, this is handled for us.</p>
<p>We will now demonstrate a multivariate K-NN regression analysis of the
Sacramento real estate data using <code>tidymodels</code>. This time we will use
house size (measured in square feet) as well as number of bedrooms as our
predictors, and continue to use house sale price as our outcome/target variable
that we are trying to predict.</p>
<p>It is always a good practice to do exploratory data analysis, such as
visualizing the data, before we start modeling the data. Thus the first thing
we will do is use ggpairs (from the <code>GGally</code> package) to plot all the variables
we are interested in using in our analyses:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="regression1.html#cb20-1"></a><span class="kw">library</span>(GGally)</span></code></pre></div>
<pre><code>## Registered S3 method overwritten by &#39;GGally&#39;:
##   method from   
##   +.gg   ggplot2</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="regression1.html#cb22-1"></a>plot_pairs &lt;-<span class="st"> </span>sacramento <span class="op">%&gt;%</span></span>
<span id="cb22-2"><a href="regression1.html#cb22-2"></a><span class="st">  </span><span class="kw">select</span>(price, sqft, beds) <span class="op">%&gt;%</span></span>
<span id="cb22-3"><a href="regression1.html#cb22-3"></a><span class="st">  </span><span class="kw">ggpairs</span>()</span>
<span id="cb22-4"><a href="regression1.html#cb22-4"></a>plot_pairs</span></code></pre></div>
<div class="figure"><span id="fig:07-ggpairs"></span>
<img src="bookdown_files/figure-html/07-ggpairs-1.png" alt="Scatterplots of each pair of variables (price, house size, and the number of bedrooms) are displayed in the figure's bottom left corner. Correlation coefficients are shown in the top right corner. The distributions of price, house size and number of bedrooms are each shown along the diagonal." width="576" />
<p class="caption">
FIGURE 7.8: Scatterplots of each pair of variables (price, house size, and the number of bedrooms) are displayed in the figure’s bottom left corner. Correlation coefficients are shown in the top right corner. The distributions of price, house size and number of bedrooms are each shown along the diagonal.
</p>
</div>
<p>From this we can see that generally, as both house size and number of bedrooms increase, so does price. Does adding the number of bedrooms to our model improve our ability to predict house price? To answer that question, we will have to come up with the test error for a K-NN regression model using house size and number of bedrooms, and then we can compare it to the test error for the model we previously came up with that only used house size to see if it is smaller (decreased test error indicates increased prediction quality). Let’s do that now!</p>
<p>First we’ll build a new model specification and recipe for the analysis. Note that
we use the formula <code>price ~ sqft + beds</code> to denote that we have two predictors,
and set <code>neighbors = tune()</code> to tell <code>tidymodels</code> to tune the number of neighbours for us.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="regression1.html#cb23-1"></a>sacr_recipe &lt;-<span class="st"> </span><span class="kw">recipe</span>(price <span class="op">~</span><span class="st"> </span>sqft <span class="op">+</span><span class="st"> </span>beds, <span class="dt">data =</span> sacramento_train) <span class="op">%&gt;%</span></span>
<span id="cb23-2"><a href="regression1.html#cb23-2"></a><span class="st">  </span><span class="kw">step_scale</span>(<span class="kw">all_predictors</span>()) <span class="op">%&gt;%</span></span>
<span id="cb23-3"><a href="regression1.html#cb23-3"></a><span class="st">  </span><span class="kw">step_center</span>(<span class="kw">all_predictors</span>())</span>
<span id="cb23-4"><a href="regression1.html#cb23-4"></a></span>
<span id="cb23-5"><a href="regression1.html#cb23-5"></a>sacr_spec &lt;-<span class="st"> </span><span class="kw">nearest_neighbor</span>(<span class="dt">weight_func =</span> <span class="st">&quot;rectangular&quot;</span>, <span class="dt">neighbors =</span> <span class="kw">tune</span>()) <span class="op">%&gt;%</span></span>
<span id="cb23-6"><a href="regression1.html#cb23-6"></a><span class="st">  </span><span class="kw">set_engine</span>(<span class="st">&quot;kknn&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb23-7"><a href="regression1.html#cb23-7"></a><span class="st">  </span><span class="kw">set_mode</span>(<span class="st">&quot;regression&quot;</span>)</span></code></pre></div>
<p>Next, we’ll use 5-fold cross-validation to choose the number of neighbours via the minimum RMSPE:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="regression1.html#cb24-1"></a>gridvals &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">neighbors =</span> <span class="kw">seq</span>(<span class="dv">1</span>, <span class="dv">200</span>))</span>
<span id="cb24-2"><a href="regression1.html#cb24-2"></a>sacr_k &lt;-<span class="st"> </span><span class="kw">workflow</span>() <span class="op">%&gt;%</span></span>
<span id="cb24-3"><a href="regression1.html#cb24-3"></a><span class="st">  </span><span class="kw">add_recipe</span>(sacr_recipe) <span class="op">%&gt;%</span></span>
<span id="cb24-4"><a href="regression1.html#cb24-4"></a><span class="st">  </span><span class="kw">add_model</span>(sacr_spec) <span class="op">%&gt;%</span></span>
<span id="cb24-5"><a href="regression1.html#cb24-5"></a><span class="st">  </span><span class="kw">tune_grid</span>(sacr_vfold, <span class="dt">grid =</span> gridvals) <span class="op">%&gt;%</span></span>
<span id="cb24-6"><a href="regression1.html#cb24-6"></a><span class="st">  </span><span class="kw">collect_metrics</span>() <span class="op">%&gt;%</span></span>
<span id="cb24-7"><a href="regression1.html#cb24-7"></a><span class="st">  </span><span class="kw">filter</span>(.metric <span class="op">==</span><span class="st"> &quot;rmse&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb24-8"><a href="regression1.html#cb24-8"></a><span class="st">  </span><span class="kw">filter</span>(mean <span class="op">==</span><span class="st"> </span><span class="kw">min</span>(mean)) <span class="op">%&gt;%</span></span>
<span id="cb24-9"><a href="regression1.html#cb24-9"></a><span class="st">  </span><span class="kw">pull</span>(neighbors)</span>
<span id="cb24-10"><a href="regression1.html#cb24-10"></a>sacr_k</span></code></pre></div>
<pre><code>## [1] 14</code></pre>
<p>Here we see that the smallest RMSPE occurs when <span class="math inline">\(K =\)</span> 14.</p>
<p>Now that we have chosen <span class="math inline">\(K\)</span>, we need to re-train the model on the entire
training data set, and after that we can use that model to predict
on the test data to get our test error.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="regression1.html#cb26-1"></a>sacr_spec &lt;-<span class="st"> </span><span class="kw">nearest_neighbor</span>(<span class="dt">weight_func =</span> <span class="st">&quot;rectangular&quot;</span>, <span class="dt">neighbors =</span> sacr_k) <span class="op">%&gt;%</span></span>
<span id="cb26-2"><a href="regression1.html#cb26-2"></a><span class="st">  </span><span class="kw">set_engine</span>(<span class="st">&quot;kknn&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb26-3"><a href="regression1.html#cb26-3"></a><span class="st">  </span><span class="kw">set_mode</span>(<span class="st">&quot;regression&quot;</span>)</span>
<span id="cb26-4"><a href="regression1.html#cb26-4"></a></span>
<span id="cb26-5"><a href="regression1.html#cb26-5"></a>knn_mult_fit &lt;-<span class="st"> </span><span class="kw">workflow</span>() <span class="op">%&gt;%</span></span>
<span id="cb26-6"><a href="regression1.html#cb26-6"></a><span class="st">  </span><span class="kw">add_recipe</span>(sacr_recipe) <span class="op">%&gt;%</span></span>
<span id="cb26-7"><a href="regression1.html#cb26-7"></a><span class="st">  </span><span class="kw">add_model</span>(sacr_spec) <span class="op">%&gt;%</span></span>
<span id="cb26-8"><a href="regression1.html#cb26-8"></a><span class="st">  </span><span class="kw">fit</span>(<span class="dt">data =</span> sacramento_train)</span>
<span id="cb26-9"><a href="regression1.html#cb26-9"></a></span>
<span id="cb26-10"><a href="regression1.html#cb26-10"></a>knn_mult_preds &lt;-<span class="st"> </span>knn_mult_fit <span class="op">%&gt;%</span></span>
<span id="cb26-11"><a href="regression1.html#cb26-11"></a><span class="st">  </span><span class="kw">predict</span>(sacramento_test) <span class="op">%&gt;%</span></span>
<span id="cb26-12"><a href="regression1.html#cb26-12"></a><span class="st">  </span><span class="kw">bind_cols</span>(sacramento_test)</span>
<span id="cb26-13"><a href="regression1.html#cb26-13"></a></span>
<span id="cb26-14"><a href="regression1.html#cb26-14"></a>knn_mult_mets &lt;-<span class="st"> </span><span class="kw">metrics</span>(knn_mult_preds, <span class="dt">truth =</span> price, <span class="dt">estimate =</span> .pred)</span>
<span id="cb26-15"><a href="regression1.html#cb26-15"></a>knn_mult_mets</span></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard   85152.   
## 2 rsq     standard       0.572
## 3 mae     standard   63575.</code></pre>
<p>This time when we performed K-NN regression on the same data set, but also
included number of bedrooms as a predictor we obtained a RMSPE test error
of 85152.
This compares to a RMSPE test error
of 87737
when we used only house size as the
single predictor. Thus in this case, we did not improve the model
by a large amount by adding this additional predictor.</p>
We can also visualize the model’s predictions overlaid on top of the data. This time the predictions
will be a surface in 3-D space, instead of a line in 2-D space, as we have 2
predictors instead of 1.
<div class="figure"><span id="fig:07-knn-mult-viz"></span>
<img src="img/lm-regr_3d.png" alt="K-NN regression model’s predictions represented as a surface in 3-D space overlaid on top of the data using three predictors; price, house size, and the number of bedrooms" width="962" />
<p class="caption">
FIGURE 7.9: K-NN regression model’s predictions represented as a surface in 3-D space overlaid on top of the data using three predictors; price, house size, and the number of bedrooms
</p>
</div>
<p>We can see that the predictions in this case, where we have 2 predictors, form
a surface instead of a line. Because the newly added predictor, number of
bedrooms, is correlated with price (USD) (meaning as price changes, so does
number of bedrooms) and not totally determined by house size (our other predictor),
we get additional and useful information for making our
predictions. For example, in this model we would predict that the cost of a
house with a size of 2,500 square feet generally increases slightly as the number
of bedrooms increases. Without having the additional predictor of number of
bedrooms, we would predict the same price for these two houses.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="classification-continued.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="regression2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yihui/bookdown-crc/edit/master/08-regression1.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown.pdf", "bookdown.epub"],
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
